rootProject.name = 'JavaDemoApiIntegration'

//TODO Create a snippet with dependencyResolutionManagement section and repositories setup
//dependencyResolutionManagement {
//  repositories {
//    mavenCentral()
//  }
//  TODO Create a snippet with the below code to setup custom versions.toml location
//  versionCatalogs {
//    create("libs") {
//      from(files("./versions.toml"))
//    }
//  }
//}