##  Application Properties
###############################
# Application name
spring.application.name=javaDemoApiIntegration

# Enable ANSI colors in console output
spring.output.ansi.enabled=always

##  Logging Configuration
###############################
# Unavailable in Spring Boot 2.x
logging.include-application-name=false

# Unavailable in Spring Boot 2.x
#logging.include-application-group=false

##  Spaceflight News API Configuration
###############################
api.spaceflight.base-url=https://api.spaceflightnewsapi.net
api.spaceflight.articles-url=/v4/articles
